export ESPFLASH_BAUD := "921600"

build: build-wat
    cargo build --release

build-wat:
    just -f wat/justfile build

run: build
    cargo run --release

clean:
    cargo clean
    just -f wat/justfile clean
