export ESPFLASH_BAUD := "921600"

default:
    just --list

build:
    cargo build --release

run: build
    cargo run --release

clean:
    cargo clean

ci:
    cargo clippy -- -D warnings
    cargo fmt --all -- --check
